version: 3

includes:
  python: ./Taskfile.python.yaml
  r: ./Taskfile.R.yaml
  rust: ./Taskfile.rust.yaml

tasks:
  copy-root-files:
    desc: Copy files from the root of the repository to the base build directories
    cmds:
      - cp ./scripts/apt-install {{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}}/apt-install
      - cp ./scripts/secrets_helper.sh {{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}}/secrets_helper.sh
    generates:
      - ./{{.LANGUAGE}}/base/{{.NBL_LANGUAGE_VERSION}}/apt-install
      - ./{{.LANGUAGE}}/base/{{.NBL_LANGUAGE_VERSION}}/secrets_helper.sh

  copy-language-files:
    desc: Copy files from the language-level directory to the build directories
    deps: [copy-root-files]
    cmds:
      - cp {{.LANGUAGE}}/Aptfile {{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}}/Aptfile
      - cp {{.LANGUAGE}}/run.sh {{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}}/run.sh
    generates:
      - ./{{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}}/Aptfile
      - ./{{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}}/run.sh

  build:
    desc: Build the kernel image with docker buildx
    cmds:
      - >-
        docker buildx build {{.LANGUAGE}}/{{.IDENTIFIER}}/{{.NBL_LANGUAGE_VERSION}} {{.CLI_ARGS}} \
          --build-arg "NBL_LANGUAGE_VERSION={{.NBL_LANGUAGE_VERSION}}" \
          --target "{{.BUILD_TARGET}}" \
          --tag "local/kernel-{{.LANGUAGE}}-{{.NBL_LANGUAGE_VERSION}}-{{.IDENTIFIER}}{{.TAG_SUFFIX}}:{{.TAG}}"
    requires:
      vars: [LANGUAGE, IDENTIFIER, NBL_LANGUAGE_VERSION]
    vars:
      BUILD_TARGET: '{{default "base" .BUILD_TARGET}}'
      TAG_SUFFIX: '{{default "" .TAG_SUFFIX}}'
      TAG: '{{default "dev" .TAG}}'
