#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

APTFILE=${1}

apt-get update -y
for package in $(cat Aptfile | grep -v -s -e '^#' | grep -v -s -e "^:repo":); do
    # Accept End User License Agreement if needed
    # (needed for some packages like msodbcsql18)
    ACCEPT_EULA=Y apt-get install -y ${package}
done
rm -rf /var/lib/apt/lists/*
