name: Build kernel images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    env:
      # TODO: This should not be SHA, but branch / tag name
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - run: |
          task python:base:copy-files NBL_PYTHON_VERSION=3.9
          task python:base:copy-files NBL_PYTHON_VERSION=3.10
          task python:base:copy-files NBL_PYTHON_VERSION=3.11
          task python:noteable:copy-files NBL_PYTHON_VERSION=3.9
          task python:noteable:copy-files NBL_PYTHON_VERSION=3.10
          task python:noteable:copy-files NBL_PYTHON_VERSION=3.11
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/bake-action@v3
        with:
          push: false
          targets: python