name: Build kernel images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  superlint:
    uses: noteable-io/actions/.github/workflows/superlint.yml@0.8.5
    secrets: inherit

  build_images:
    strategy:
      matrix:
        identifier:
          - 'base'
          - 'datascience'
          - 'noteable'
        version:
          - 3.9
          - 3.10
          - 3.11
        gpu_suffix:
          - '-gpu'
          - ''
    name: python ${{ matrix.version }} - ${{ matrix.identifier }}-${{ matrix.gpu_suffix }}
    uses: noteable-io/actions/.github/workflows/docker.yml@0.8.5
    secrets: inherit
    with:
      context: ./python/${{ matrix.identifier }}${{ matrix.gpu_suffix }}
      enable_comments: false
      aws_account_id: ''
      images: |
        ghcr.io/noteable-io/kernel${{ matrix.gpu_suffix }}-python-${{ matrix.identifier }}-${{ matrix.version }}
      build_args: |
        NBL_PYTHON_VERSION=${{ matrix.version }}
      tags: |
        type=sha,format=long
  
  build_r_images:
    strategy:
      matrix:
        identifier:
          - base
        version:
          - 4.3
    name: ${{ matrix.identifier }} / ${{ matrix.version }}
    uses: noteable-io/actions/.github/workflows/docker.yml@0.8.5
    secrets: inherit
    with:
      context: ./R
      enable_comments: false
      aws_account_id: ''
      images: |
        ghcr.io/noteable-io/kernel-r-${{ matrix.version }}
      build_args: |
        NBL_R_VERSION=${{ matrix.version }}
      tags: |
        type=sha,format=long